### ISSUE TITLE
convert to valid onnx file

### ISSUE THREAD

**Issue by ghost** [margaretmz/CartoonGAN-e2e-tflite-tutorial#1]
I am using tf2onnx to convert the pb file to onnx
!python -m tf2onnx.convert --saved-model /content/saved_model_dir/ --output model.onnx --opset 10 to get a onnx file but get this error when parsing
The ONNX model's slice layer input const_slice__92 must be a 1-dimensional constant tensor

**Comment by sayakpaul** [comment]
Please file this issue in the appropriate ONNX repository.

**Comment by ghost** [comment]
@sayakpaul ok do you know how freeze graph to pb instead of getting saved_model.pb?

**Comment by sayakpaul** [comment]
Following resources could be useful:
- https://gist.github.com/moodoki/e37a85fb0258b045c005ca3db9cbc7f6
- https://medium.com/@prasadpal107/saving-freezing-optimizing-for-inference-restoring-of-tensorflow-models-b4146deb21b5
- https://cv-tricks.com/how-to/freeze-tensorflow-models/

**Comment by ghost** [comment]
@sayakpaul I think it is missing the .meta file so a frozen graph cannot be obtained

**Comment by sayakpaul** [comment]
Okay. But I would do a bit more digging around to ensure that's the case.

**Comment by ghost** [comment]
@sayakpaul https://stackoverflow.com/questions/45864363/tensorflow-how-to-convert-meta-data-and-index-model-files-into-one-graph-pb
it seems it is needed, were you able to get it working as a frozen graph?

**Comment by sayakpaul** [comment]
I did not try that out. You may out want to open an issue on the [original model repository](https://github.com/SystemErrorWang/White-box-Cartoonization) and ask the authors if they have the frozen graph.
