### ISSUE TITLE
Clarity in metadata population

### ISSUE THREAD

**Issue by sayakpaul** [margaretmz/CartoonGAN-e2e-tflite-tutorial#2]
@khanhlvg here's how I prepared the post-processing stats for populating metadata:

```python
# Creates output info, cartoonized image
    output_image_meta = _metadata_fb.TensorMetadataT()
    output_image_meta.name = "cartoonized_image"
    output_image_meta.description = "Image cartoonized."
    output_image_meta.content = _metadata_fb.ContentT()
    output_image_meta.content.contentProperties = _metadata_fb.ImagePropertiesT()
    output_image_meta.content.contentProperties.colorSpace = (
        _metadata_fb.ColorSpaceType.RGB)
    output_image_meta.content.contentPropertiesType = (
        _metadata_fb.ContentProperties.ImageProperties)
    # output_image_normalization = _metadata_fb.ProcessUnitT()
    # output_image_normalization.optionsType = (
    #     _metadata_fb.ProcessUnitOptions.NormalizationOptions)
    # output_image_normalization.options = _metadata_fb.NormalizationOptionsT()
    # output_image_normalization.options.mean = [0.0]
    # output_image_normalization.options.std = [0.003921568627]  # 1/255
    # output_image_meta.processUnits = [output_image_normalization]
    output_image_stats = _metadata_fb.StatsT()
    output_image_stats.max = [255.0]
    output_image_stats.min = [0.0]
    output_image_meta.stats = output_image_stats
```

What would be the best way to account for the fact that the output needs to be scaled to [0,255]?

**Comment by khanhlvg** [comment]
This should work. You'll have to do similarly with the input info so that it won't normalize [0..255] input to [0.0, 1.0]

```
# Creates output info, cartoonized image
    output_image_meta = _metadata_fb.TensorMetadataT()
    output_image_meta.name = "cartoonized_image"
    output_image_meta.description = "Image cartoonized."
    output_image_meta.content = _metadata_fb.ContentT()
    output_image_meta.content.contentProperties = _metadata_fb.ImagePropertiesT()
    output_image_meta.content.contentProperties.colorSpace = (
        _metadata_fb.ColorSpaceType.RGB)
    output_image_meta.content.contentPropertiesType = (
        _metadata_fb.ContentProperties.ImageProperties)
    output_image_normalization = _metadata_fb.ProcessUnitT()
    output_image_normalization.optionsType = (
        _metadata_fb.ProcessUnitOptions.NormalizationOptions)
    output_image_normalization.options = _metadata_fb.NormalizationOptionsT()
    output_image_normalization.options.mean = [0.0]
    output_image_normalization.options.std = [1.0]
    output_image_meta.processUnits = [output_image_normalization]
    output_image_stats = _metadata_fb.StatsT()
    output_image_stats.max = [255.0]
    output_image_stats.min = [0.0]
    output_image_meta.stats = output_image_stats
```

**Comment by sayakpaul** [comment]
Thanks, @khanhlvg. Could you verify [this Colab Notebook](https://colab.research.google.com/github/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/ml/metadata/Add_Metadata.ipynb) once you get a moment?

**Comment by khanhlvg** [comment]
@sayakpaul 
The input needs to be changed to this:
```
input_image_normalization.options.mean = [0.0]
    input_image_normalization.options.std = [1.0]
```
and
```
input_image_stats.max = [255.0]
input_image_stats.min = [0.0]
```

Is the difference between the metadata of the float16 model and the other models is just the description of input image
in `input_image_meta.description`? If that's the case, maybe it's better to putting the code into a function for reuse to avoid duplicating a large chunk of code :)

**Comment by sayakpaul** [comment]
@khanhlvg 

I followed this [Colab Notebook](https://colab.research.google.com/drive/1xXFOHgdZELCtueEC9Whqx1z9ebKLhc5c) you shared for the segmentation models since the input data preprocessing steps are the same (except for BGR). 

> Is the difference between the metadata of the float16 model and the other models is just the description of input image
in input_image_meta.description? If that's the case, maybe it's better to putting the code into a function for reuse to avoid duplicating a large chunk of code :)

Yes, I have that on my mind.

**Comment by khanhlvg** [comment]
> I followed this Colab Notebook you shared for the segmentation models since the input data preprocessing steps are the same (except for BGR).

Actually the Deeplab segmentation model and the CartoonGAN models require different normalization config.
* DeepLab: normalize int8 [0..255] to float32 [-1, 1]
* ESRGAN: normalize int8 [0..255] to float32 [0.0, 255.0]

Therefore, the related parameters on the metadata needed to be updated :)

**Comment by sayakpaul** [comment]
Okay. Then I'm a bit confused here since in the preprocessing steps for CartoonGAN, we are performing ([notebook](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/CartoonGAN_TFLite.ipynb)):

```python
image = image.astype(np.float32)/127.5 - 1
image = np.expand_dims(image, axis=0)
```

**Comment by khanhlvg** [comment]
Oh very sorry, I also got confused between the ESRGAN model and the CartoonGAN model. It should be like this.
* DeepLab and CartoonGAN: normalize int8 [0..255] to float32 [-1, 1]
* ESRGAN: normalize int8 [0..255] to float32 [0.0, 255.0]

My assumption is that @margaretmz 's issue with the color being off is caused by the ESRGAN metadata is incorrect.

FYI this is the [documentation](https://www.tensorflow.org/lite/convert/metadata#normalization_and_quantization_parameters) on how TF Lite parse normalization parameters.
* For mean=127.5 and std=127.5, it converts [0..255] to [-1, 1]
* For mean=0.0 and std=1.0, it converts [0..255] to [0.0, 255.0]

**Comment by sayakpaul** [comment]
Thanks, @khanhlvg. So, apart from the code duplication issue, is that Colab Notebook (CartoonGAN metadata) alright?

**Comment by khanhlvg** [comment]
> So, apart from the code duplication issue, is that Colab Notebook (CartoonGAN metadata) alright?

Yes it is. Thanks Sayak!

**Comment by sayakpaul** [comment]
Notebook (metadata) has been cleaned.
