### ISSUE TITLE
Create markdown to include links to tflite models 

### ISSUE THREAD

**Issue by margaretmz** [margaretmz/CartoonGAN-e2e-tflite-tutorial#5]
Under the [ml](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/tree/master/ml) folder, add a markdown witha bit info about the tflite models. Just need links to models and any necessary barely minimum info. We can wait till after tutorial is complete to make it elaborative.

**Comment by sayakpaul** [comment]
I added them [here](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial#models-available-here-populated-with-metadata). Later today I will also add the links to download the fixed input shaped models (without metadata).
