### ISSUE TITLE
Publishing the TFLite models (with metadata) on TF Hub

### ISSUE THREAD

**Issue by sayakpaul** [margaretmz/CartoonGAN-e2e-tflite-tutorial#6]
@margaretmz @khanhlvg

As per our discussion [here](https://github.com/ml-gde/e2e-tflite-tutorials/issues/9) we decided to go with fixed-shaped TFLite models (520x520). Also, the models **_are not_** metadata populated yet which also came as one of the decisions in the aforementioned thread. With better model binding support in the coming days, we can release v2 of these models. WDYT? 

All the models are temporarily hosted on a GCS bucket. I have included the links [here](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/README.md#models-supporting-520x520-images-without-metadata). 

I have also included a [fresh notebook](https://colab.research.google.com/github/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/ml/CartoonGAN_TFLite_Fixed_Shaped.ipynb) to demo the conversion and Python inference process.

Let me know what y'all think about the TF Hub publication step from here.

**Comment by khanhlvg** [comment]
Thanks Sayak! If we decided to go with fixed shape model for now, could you populate the metadata to those model? It will allow Margaret to integrate the model using Android Studio using the ML Model Binding plugin without writing a lot of boilerplate code.

> Let me know what y'all think about the TF Hub publication step from here.

Let's publish v1 int8 and dynamic range model with metadata and fixed shape to TF Hub first as the fp16 model doesn't run on GPU delegate anyway.

**Comment by sayakpaul** [comment]
@khanhlvg as per this discussion I did not populate the metadata in these models. @margaretmz tried the metadata populated models as well but the results came to be spurious. Margaret and I had a few doubts regarding the metadata parameters. Margaret, would you like to chime in here? 

> the fp16 model doesn't run on GPU delegate anyway.

Ahh, I didn't know it. Is there anything we could do about it?

**Comment by khanhlvg** [comment]
> @khanhlvg as per this discussion I did not populate the metadata in these models. @margaretmz tried the metadata populated models as well but the results came to be spurious. Margaret and I had a few doubts regarding the metadata parameters. Margaret, would you like to chime in here?

My understanding is Margaret's issue with the metadata came from the fact that she tried the dynamic shape model with ML Model Binding and got a weird error. It is because ML Model Binding doesn't support dynamic shape model yet. 

> > the fp16 model doesn't run on GPU delegate anyway.
> Ahh, I didn't know it. Is there anything we could do about it?

Unfortunately no. It comes from a limitation of the TF Lite GPU delegate. We need the TF Lite GPU team to work on it.

**Comment by sayakpaul** [comment]
Okay. I will populate the metadata with what we discussed [here](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/issues/2).

**Comment by sayakpaul** [comment]
@khanhlvg another point on the float16 model. Could we include it in the v1 release which might make the release more complete?

**Comment by sayakpaul** [comment]
@khanhlvg @margaretmz 

Models have been populated with metadata. Download links available [here](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/README.md#models-supporting-520x520-images-without-metadata). Here's the [Colab Notebook](https://colab.research.google.com/github/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/ml/metadata/Add_Metadata.ipynb).

**Comment by khanhlvg** [comment]
Thanks Sayak!

> @khanhlvg another point on the float16 model. Could we include it in the v1 release which might make the release more complete?

The fp16 models is larger and slower than the int8/dynamic range quantized models on CPU so I think there's no use of it. However I don't have a strong opinion on whether to publish it or not so I'll let you decide :)

**Comment by sayakpaul** [comment]
For completion, I would keep it in the release. Would you advise to include a note on the current incompatibility of the models with TFLite GPU delegate?

**Comment by khanhlvg** [comment]
> For completion, I would keep it in the release. Would you advise to include a note on the current incompatibility of the models with TFLite GPU delegate?

Sure. You can just say that the CartoonGAN model is currently not compatible with TF Lite GPU delegate.

**Comment by sayakpaul** [comment]
Fair enough!

**Comment by margaretmz** [comment]
@sayakpaul please make the following updates:
* image size should be 512x512 per discussion [here](https://github.com/ml-gde/e2e-tflite-tutorials/issues/9#issuecomment-664769791).
* edit the title of this issue and README to be (with metadata) if your models indeed contain metadata.
* I tried the 3 models what you listed most recently. The FP16 one was crashing on Android not sure why but it wasn't crashing before. The other 2 models resulted in black images on Android - I figured out it's due to incorrect metadata. Please fix it according to this issue I opened [here](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/issues/7).

**Comment by khanhlvg** [comment]
> The FP16 one was crashing on Android not sure why but it wasn't crashing before.

It crashes if you use GPU delegate. Maybe you didn't try with GPU delegate before?

**Comment by sayakpaul** [comment]
@margaretmz feedback addressed as per https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/issues/7. 

Not sure about the FP16 model crashing on Android, though.

**Comment by margaretmz** [comment]
> It crashes if you use GPU delegate. Maybe you didn't try with GPU delegate before?

I created a new app, imported the FP16 model with metadata and didn't check the "GPU delegate option". It still crashes and I can't seem to find the error in Logcat. 
@khanhlvg could you take a look at the [FP16 ](https://storage.googleapis.com/cartoon_gan/fixed_shaped_models/with_metadata/whitebox_cartoon_gan_fp16.tflite)model in Android?

**Comment by sayakpaul** [comment]
Thanks for the update, @margaretmz. Once we are clear on the models I will go ahead and create a PR on TF Hub. We could accompany our tutorial with these TF Hub models. WDYT?

**Comment by khanhlvg** [comment]
> I created a new app, imported the FP16 model with metadata and didn't check the "GPU delegate option". It still crashes and I can't seem to find the error in Logcat.

I suspect that the model use too much memory so Android OS killed the process. This is what it look like when I run the model from an Android app.

![image](https://user-images.githubusercontent.com/5379361/89389992-18f86700-d741-11ea-84eb-6e1b6be21691.png)

This is the result from the benchmark app.

```Peak memory footprint (MB): init=0.988281 overall=618.25```

The model runs fine with the benchmark app because the app doesn't have a rich UI so it consume less memory. The dynamic range and int8 quantized model also consume about 4 times less memory.

I tried reducing the model input shape to 384 * 384 and it runs fine from an Android app.

@sayakpaul If you publish the fp16 model to TF Hub, can you reduce its input shape?

**Comment by sayakpaul** [comment]
@khanhlvg sure thing. We can also make a note about this on TF Hub and in our upcoming tutorial as well. 

WDYT?

Cc: @margaretmz

**Comment by khanhlvg** [comment]
> sure thing. We can also make a note about this on TF Hub and in our upcoming tutorial as well.

SGTM!

@margaretmz Thanks for spotting the issue. :)

**Comment by sayakpaul** [comment]
Exported float16 model with reduced input shape and populated with metadata. 

[This section](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/README.md#models-supporting-512x512-images-with-metadata) has been updated too. 

Cc: @khanhlvg @margaretmz

**Comment by margaretmz** [comment]
@khanhlvg it was indeed a memory issue! This explains why original 224x224 worked fine but then stopped working after updating to 512x512.

Even with the reduced image size of 384x384, the app died on an older budget phone with 3GB memory; however, it works fine on my Pixel 4 (6GB RAM). My thoughts:

- For showing a small image on a a phone (especially side by side with the original image), I'm thinking 224x224 image resolution maybe sufficient. We can give it a try for the FP16 one.
- For the sake of a sample app, being able to running only on newer high-end phone is OK. We could also specify that under the "Requirements" section under Android instructions on project GitHub repo.

**Comment by sayakpaul** [comment]
If the int8 and the DR models run on an older budget phone I think we can drop the FP16 model for now. It won't anyway run on the GPU. WDYT?

**Comment by margaretmz** [comment]
> If the int8 and the DR models run on an older budget phone I think we can drop the FP16 model for now. It won't anyway run on the GPU. WDYT?

My answer is 'yes' and 'no':
* For the purpose of publishing tflite models on TF Hub, we should choose the best ones for wide developer adoption on most devices. Plus it won't even run on GPU. So yes drop it from the release candidates for now.
* For the purpose of an  E2E TFLite tutorial with a sample app, including the FP16 variant is a  great demo of quantization trade-offs, and a good story to tell in the tutorial. So I'd like to keep it in the sample app.

**Comment by sayakpaul** [comment]
Sounds good @margaretmz. Your points make sense. Here's what I propose:

- We include 224x224 fp16 model in both the TF Hub bundle and the tutorial. We make a note about the limitations of the fp16 model. 

WDYT?

Upon this decision, I will:
- Create a 224x224 fp16 model and will populate that with metadata.
- Update the download links so that it's easier for you to navigate. 
- Create a PR on Hub.

**Comment by margaretmz** [comment]
Sounds like a good plan. Thanks @sayakpaul!

**Comment by sayakpaul** [comment]
@margaretmz models updated [here](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/README.md#models-with-metadata-supporting-512x512-images).

**Comment by margaretmz** [comment]
Excellent! Here is what the 224x224 FP16 model looks like:

![image](https://user-images.githubusercontent.com/1885008/89446023-d024bc00-d708-11ea-9b8b-4b72676a9131.png)

By the way, a few minor corrections:
* update the title of this issue remove ("without metadata")
* on the main [README](https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/README.md#models-with-metadata-supporting-512x512-images) - should be 224x224, not 384x384

**Comment by sayakpaul** [comment]
Thanks @margaretmz. Updates have been made.

**Comment by sayakpaul** [comment]
PR has been created: https://github.com/tensorflow/hub/pull/654.
