### ISSUE TITLE
Fix metadata in tflite models

### ISSUE THREAD

**Issue by margaretmz** [margaretmz/CartoonGAN-e2e-tflite-tutorial#7]
I figured out the (black) image issue on Android! It was caused by incorrect image post processing (from tflite metadata).

@sayakpaul please fix the metadata in the tflite models as follows:
update from
`
  output_image_normalization.options.mean = [0.0]
    output_image_normalization.options.std = [1.0]
`
to 
`output_image_normalization.options.mean = [-1].   
 output_image_normalization.options.std = [0.00784313]  # 1/127.5`

I have verified that this will mirror the post processing in the conversion notebook, and it works on Android.

cc: @khanhlvg

When adding metadata to the tflite models, I also find it helpful to put a date stamp in the version code for example something like this: v3_2020-08-03. Otherwise it's really difficult for me to keep track of the various model versions.

**Comment by margaretmz** [comment]
FYI here is what the int8 one look like on Android after I fixed the metadata issue:

![image](https://user-images.githubusercontent.com/1885008/89251704-8c2c9c80-d5cc-11ea-8808-90b864caa214.png)

I'm excited to finish the app and looking forward to our E2E tutorial.

**Comment by khanhlvg** [comment]
This is super exciting! Thanks Margaret :)

**Comment by sayakpaul** [comment]
@margaretmz thanks so much for your hard work on this. I have updated everything as per your feedback. 

Updated Colab Notebooks:
- [`CartoonGAN_TFLite_Fixed_Shaped.ipynb`](https://colab.research.google.com/github/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/ml/CartoonGAN_TFLite_Fixed_Shaped.ipynb)
- [`ml/metadata/Add_Metadata.ipynb`](https://colab.research.google.com/github/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/ml/metadata/Add_Metadata.ipynb)

Model files:
- https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/blob/master/README.md#models-supporting-512x512-images-with-metadata

Let me know if anything is unclear.

**Comment by margaretmz** [comment]
Thanks @sayakpaul for the updates! The int8 and dr models now work in Android. 
FP16 one still crashes and I asked @khanhlvg to help take a look at it.

**Comment by sayakpaul** [comment]
Fair enough @margaretmz. Thank you for the updates.

**Comment by sayakpaul** [comment]
Closing this issue. As @khanhlvg provided some guidance here: https://github.com/margaretmz/CartoonGAN-e2e-tflite-tutorial/issues/6
